### ISSUE TITLE
Stripe Connect does not finish anymore

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/theme#125]
My `pippins-ebooks` store is showing that I have not connected to Stripe. I attempted to connect to Stripe and it appeared to work (I got redirected back to my dashboard) but the connected status never changed.

I also do not see the account linked in Stripe.

**Comment by DrewAPicture** [comment]
After some experimentation, it looks like the secondary request sent via `connect_accounts()` is running up against a 403 Forbidden error that I can't seem to diagnose. I was able to capture the code sent from the first connection request and send the second request directly via Postman and it returned the expected object, so I'm not sure if this is a WordPress-specific problem or what. Just wanted to leave a note for future reference.

**Comment by amdrew** [comment]
@DrewAPicture Any further luck on this?

**Comment by mindctrl** [comment]
I was seeing the same 403 error using `wp_remote_post` in RCP, yet `curl` worked fine.

Turns out I needed to pass a `user-agent` to `wp_remote_post` for it to work.

The default user-agent WP sends appears to be: `'WordPress/' . get_bloginfo( 'version' ) . '; ' . get_bloginfo( 'url' )`. For whatever reason that does not work.

In my testing, I'm just passing `'RCP Development - https://rcp-dev.dev'` and it works fine.
