### ISSUE TITLE
Improve product delete UI

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#132]
When you click to delete a product, it shows a "Delete product" screen. 

The confirmation box seems a bit confusing. To cancel you would have to select the `No, cancel` radio input, and then click `Delete product`. Clicking the label for the `No, cancel` doesn't select the input but if we're going to change it, it doesn't matter.

How about we change this to a simple "delete" button (red), and a "no, cancel" link beside it. Or even 2 buttons side-by-side.

Sidenote: In the future I'd like to see this screen removed, and just show a modal confirmation for deleting a product.

**Comment by DrewAPicture** [comment]
This is a somewhat unorthodox idea but I'd even be inclined to not actually allow deleting products, or at least ourselves as far as store managers are concerned. This b is because actually deleting products have much wider implications for subscriptions down the road, completed orders, commissions, all sorts of things that can go haywire when there's missing data.

We could still present it as a "deletion" action but I think we should "deactivate" them with a custom status.

**Comment by amdrew** [comment]
Could we not show in the confirmation message what exactly could go wrong for that specific product, if it is deleted? And then its on the user should anything go wrong. I haven't seen a system so far in my travels that doesn't allow you to delete a product.

**Comment by DrewAPicture** [comment]
There are plenty of online stores that show "discontinued" products but I rarely see old products get actually straight up removed. That's what I'm getting at. "Deleted" is a strong word, and again, I would caution against actually allowing removal of the original record, regardless of whether we actually call it "delete" or something else.
