### ISSUE TITLE
Dismiss home notices

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#133]
In the future, there might be more notices shown on the home screen. Some of these notices (some are important and should remain visible) should be dismissible.

**Comment by amdrew** [comment]
The third notice in the image below is an example of a notice that can be dismissed. Currently it can be dismissed, however it needs to be hooked up so it doesn't reappear on page refresg. A flag in usermeta seems to be the best option for this.

<img width="1160" alt="screen shot 2018-03-30 at 1 41 14 pm" src="https://user-images.githubusercontent.com/52581/38224095-6a466f72-3742-11e8-92c0-a489de2a96c7.png">

The above dismissible notice (and the other shown) can be tested in the PR at #184

**Comment by pippinsplugins** [comment]
These look lovely!

**Comment by DrewAPicture** [comment]
Let's not use user meta for the notices, mostly because I'd rather not hit usermeta every time to decide whether or not to display it. Maybe a store option with dismissed notices?

**Comment by amdrew** [comment]
Ahh yeah I like that. No need for it to be user-specific when the notices will be at the store level 👍

**Comment by DrewAPicture** [comment]
Added a PR, #214, which completely refactors how the notices API works, relying on a registry to standardize retrieval and output, vs the giant switch statement ;)

**Comment by DrewAPicture** [comment]
With the conclusion of #214. I've started a new WIP PR: #215, which handles the actual saving of the dismiss action facilitated by bootstrap.

**Comment by DrewAPicture** [comment]
With the merge of #215, this is done.

I completely rewrote how notices work to leverage a registry. Dismissed notice options are stored by user and notice ID in options table for each store. Any notice registered with the 'close' value of 'dismissible' will automatically inherit a bootstrap-compatible X (close) button that can trigger the dismiss Ajax.

Bootstrap handles initially hiding the notice, the Ajax (hooked to a close event fired by Bootstrap JS) handles saving the dismissed state.

The default 'close' value is 'auto', which I'm gonna separately setup JS to auto-hide after X number of seconds. Finally, a 'persistent' value for the 'close' attribute is just that: not subject to an X (close) button and not auto-hidden.

Supported 'type' values line up with the bootstrap alert classes for 'success', 'warning', 'info', and 'danger'.

All notices should be registered (currently happening in class-dashboard.php), and there's compat support for RCP notice handling too. The general rule of thumb is that every notice should serve exactly one purpose, as evidenced by the addition of some new manager-related notices, i.e. manager-exists, manager-error, etc.

To print a notice in the UI, such as on the dashboard.php template, each notice is registered and then we can directly call `print_notice( $notice_id );` in place and the notices API will determine what to output based on the above.

Example registrations from class-dashboard.php:
```php
// Account expired but in the grace period.
$this->notices->register_notice( 'store-expired-grace-period', array(
    'message' => array( $this, 'get_store_expired_notice' ),
    'type'    => 'info',
) );

// Account expired.
$this->notices->register_notice( 'store-expired', array(
    'message' => '<strong>Your account has expired!</strong> Please renew your account in order to reactivate your SellBird site.',
    'type'    => 'info',
) );
```

Example usage of `print_notice()` from dashboard.php:
```php
if( ! rcp_is_expired() && get_user_meta( get_current_user_id(), 'sellbird_in_grace_period', true ) ) :
    print_notice( 'store-expired-grace-period' );
elseif ( rcp_is_expired() ) :
    print_notice( 'store-expired' );
endif;
```

For notices triggered via the URL, it works exactly the same as before, except that all notices are now using the registry instead of a giant switch statement (and see the note about one notice one purpose). Notices triggered via the URL are still output via the `sellbird_dashboard_notices` action.

**Comment by DrewAPicture** [comment]
With the merge of #215, this is complete.

## Overview
I completely rewrote how notices work to leverage a registry. Dismissed notice options are stored by user and notice ID in options table for each store. Any notice registered with the 'close' value of 'dismissible' will automatically inherit a bootstrap-compatible X (close) button that can trigger the dismiss Ajax:

```php
$this->notices->register_notice( 'foo', array(
    'message' => 'This is a message.',
    close'    => 'dismissible',
) );
```

## Saving Dismissed State via Ajax
Bootstrap handles initially hiding the notice, the Ajax (hooked to a close event fired by Bootstrap JS) handles saving the dismissed state.

The default 'close' value is 'auto', which I'm gonna separately setup JS to auto-hide after X number of seconds. Finally, a 'persistent' value for the 'close' attribute is just that: not subject to an X (close) button and not auto-hidden.

## Notice Types
Supported 'type' values line up with the bootstrap alert classes for 'success', 'warning', 'info', and 'danger'.

## Registration and Compat
All notices should be registered (currently happening in class-dashboard.php), and there's compat support for RCP notice handling too. The general rule of thumb is that every notice should serve exactly one purpose, as evidenced by the addition of some new manager-related notices, i.e. manager-exists, manager-error, etc.

## Printing Notices Manually
To print a notice in the UI, such as on the dashboard.php template, each notice is registered and then we can directly call `print_notice( $notice_id );` in place and the notices API will determine what to output based on the above.

## Printing Notices via the URL (most of our notices)
For notices triggered via the URL, it works exactly the same as before, except that all notices are now using the registry instead of a giant switch statement (and see the note about one notice one purpose). Notices triggered via the URL are still output via the `sellbird_dashboard_notices` action.

## Examples
Example registrations from class-dashboard.php:
```php
// Account expired but in the grace period.
$this->notices->register_notice( 'store-expired-grace-period', array(
    'message' => array( $this, 'get_store_expired_notice' ),
    'type'    => 'info',
) );

// Account expired.
$this->notices->register_notice( 'store-expired', array(
    'message' => '<strong>Your account has expired!</strong> Please renew your account in order to reactivate your SellBird site.',
    'type'    => 'info',
) );
```

Example usage of `print_notice()` from dashboard.php:
```php
if( ! rcp_is_expired() && get_user_meta( get_current_user_id(), 'sellbird_in_grace_period', true ) ) :
    print_notice( 'store-expired-grace-period' );
elseif ( rcp_is_expired() ) :
    print_notice( 'store-expired' );
endif;
```

**Comment by pippinsplugins** [comment]
Love this, super slick!

**Comment by DrewAPicture** [comment]
Auto-hide is now done too after #216.
