### ISSUE TITLE
Turn off variable pricing by default

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#137]
While adding a new product, the `Set as default` radio input, the `remove` link and `add price` button all show. I don't have any data, but I'm going to assume most digital products will be a single priced product.

I like the way EDD handles it, you need to enable variable pricing if you want to have more than 1 price for the product.

I think we should follow suit, anyone agree? We should try and keep the interface as simple as possible and only expose options if the user needs them.

**Comment by pippinsplugins** [comment]
@DrewAPicture and I discussed this a bit a few weeks ago. We felt that EDD's method, while natural to us, is probably unnatural actually and only feels natural because we're so used to it.

I would be inclined to only provide a UI that supports multiple prices instead of trying to have two different UIs. If a product owner only wants a single price, they only need to add one. We can adjust the display on the frontend like we already do in EDD.

**Comment by amdrew** [comment]
Right, I agree with that. Closing!
