### ISSUE TITLE
Replace image button not working

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#150]
When you click the "replace" button on the edit product screen, it removes the image and shows the replace button, but there's no way to then select a new one. Clicking the button doesn't seem to work.

**Comment by DrewAPicture** [comment]
So, the default for image upload in this workflow is just a file input with a Browse button. When you click [Replace] it removes the image preview and "resets" back to just the file input.

Note that we don't really have a lot of options on using an actual upload button separate from the default Browse button that comes with the control. This is because file uploads typically require the form to actually be submitted – right now we're hooked to the change event on the file input – which means we'd have to sacrifice the instant gratification of a preview if we had to go back to tying to submit.

So if you're wanting to improve the flow, maybe some help text would suffice.

**Comment by amdrew** [comment]
Should be now able to replace images as intended. To test, use the PR linked from #184.
