### ISSUE TITLE
Upload a store logo during registration

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#27]
Having logo controls in Dashboard  > Settings is a must, but we should definitely have the ability to upload a logo from the outset on registration.

**Comment by DrewAPicture** [comment]
I've opened https://github.com/restrictcontentpro/rcp-site-creation/issues/37 as an attempt to make adding custom registration fields a bit easier.

**Comment by amdrew** [comment]
I don't think we should allow someone to upload a logo during registration, it feels like an unnecessary barrier. While researching other systems it's also not something I ever saw, probably due to that reason.

Uploading a logo is something the user should do after registration, either during the on-boarding steps (https://github.com/SellBirdHQ/theme/issues/30) or from the dashboard settings page.

**Comment by DrewAPicture** [comment]
I'm on board. Plus, it occurred to me yesterday that to enable that, we'd have to effectively allow users to do unprivileged file uploads, which doesn't appeal to me from a security perspective. Closing as wontfix (though having the related hooks added to RCP Site Creation could still be potentially useful outside of this discussion).

**Comment by amdrew** [comment]
Good point on security, 👍 to the hooks
